### ISSUE TITLE
Extra comma in instructions

### ISSUE THREAD

**Issue by ciberado** [alexa/skill-sample-nodejs-petmatch#11]
Hi,

if I'm not wrong this line 
```
$ ask simulate -l en-US -t "alexa, start pet match"
```
has an extra comma that prevents it's invocation (should be `$ ask simulate -l en-US -t "alexa start pet match"`)

**Comment by aszk** [comment]
Thank you for reporting the issue. However `ask simulate` was removed hence it is not relevant. Reference: https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-v1-to-v2-migration-guide.html#remove-ask-simulate
We need to work on recreating the instruction.
