### ISSUE TITLE
Pet Match code sample for en-GB language

### ISSUE THREAD

**Issue by jquintozamora** [alexa/skill-sample-nodejs-petmatch#19]
I've tried to deploy Pat Match V2 code sample using "en-GB" language and I've got an unexpected error when try to invocate the skill:

```
$ ask simulate -l "en-GB" -t "Alexa open pet match"     
✓ Simulation created for simulation id: caba99b3-4699-4359-aece-d4a4fd884ff9
◜ Waiting for simulation response{
  "id": "caba99b3-4699-4359-aece-d4a4fd884ff9",
  "status": "FAILED",
  "result": {
    "error": {
      "message": "An unexpected error occurred."
    }
  }
}
```

Any ideas why should It be? 
Thanks in advance

**Comment by aszk** [comment]
Thank you for your question. `ask simulate` is removed. Reference: https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-v1-to-v2-migration-guide.html#remove-ask-simulate
We provide couple of ways to test your skills. Could you try one of these?
-  [Please try it on Alexa Developer Console or Echo device. ](https://developer.amazon.com/en-US/blogs/alexa/alexa-skills-kit/2021/12/how-to-test-your-alexa-skills-on-developer-console)
- https://developer.amazon.com/de-DE/docs/alexa/ask-toolkit/vs-code-testing-simulator.html
- https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-intro.html#prepare-to-test-your-local-alexa-skill
