### ISSUE TITLE
Wrong Lambda?

### ISSUE THREAD

**Issue by kennyray** [alexa/skill-sample-nodejs-petmatch#20]
The instructions are saying to use "alexa-skills-kit-nodejs-factskill", but that doesn't seem right to me. Should there not be one specific to this project? I tried searching "alexa-skills-kit-nodejs-pet" and it did not find anything...

**Comment by SleepyDeveloper** [comment]
Sorry the instructions aren't clear enough. After you create your lambda function, you will replace the default code by copying and pasting the pet match code into the lambda code editor.
