### ISSUE TITLE
"here" link in step 12 of "2-lambda-function.md" is broken

### ISSUE THREAD

**Issue by cargiggles** [alexa/skill-sample-nodejs-petmatch#22]
**File:**
https://github.com/alexa/skill-sample-nodejs-petmatch/blob/master/instructions/2-lambda-function.md

**Issue:**
12. If you want to **secure this Lambda function** follow the instructions found [here](https://github.com/alexa/alexa-cookbook/blob/master/aws/secure-lambda-function.md)

Note: https://github.com/alexa/alexa-cookbook/blob/master/aws/secure-lambda-function.md directs to a 404

**Comment by aszk** [comment]
The instruction has been updated. The links have been removed from the instruction.
