### ISSUE TITLE
Does this work for ASK CLI?

### ISSUE THREAD

**Issue by jamielliottg2** [alexa/skill-sample-nodejs-petmatch#24]
I'm getting:

```
{
  "errorMessage": "Unexpected identifier",
  "errorType": "SyntaxError",
  "stackTrace": [
    "Object.runInThisContext (vm.js:97:10)",
    "Module._compile (module.js:542:28)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}
```

**Comment by jamielliottg2** [comment]
Fixed by removing the , on 399

**Comment by jamielliottg2** [comment]
Looks like using 8.1 node fixes it

**Comment by gilleswb** [comment]
CLI insstructions confirms following prerequisite to use ask-CLI including Node.js (> v8)

Please refer to following to try sample with ask-cli successfully
https://github.com/alexa-samples/skill-sample-nodejs-petmatch/blob/master/instructions/7-cli.md

Already confirmed by reporter to be resolved on Node.js v8.1. Closing this Issue as resolved
