### ISSUE TITLE
Few warnings

### ISSUE THREAD

**Issue by Veiam** [alexa/skill-sample-nodejs-petmatch#8]
Hello all,

In index.js

Line 162 is missing a semicolon.
Line 181 is missing a semicolon.
Line 231 is missing a semicolon.
Line 363, `filledSlots` is defined but never used again.
Line 365 has an unnecessary semicolon.
Line 378 is unreachable due to `return` in Line 377.
Line 435 is missing a semicolon.
Line 453, `currentIntent` is defined but never used again.
Line 457, `slotValue` is defined but never used again.

**Comment by aszk** [comment]
Thank you for reporting those issues and I am sorry for the late reply. However index.js has been updated and it doesn't look relevant anymore.
